[package]
name = "nice"
version = "0.0.18"
description = "Bindings for libnice >= v0.1.4"
homepage = "https://github.com/manuels/libnice.rs"
license = " GPL-2.0"
authors = ["Manuel Schölling <manuel.schoelling@gmx.de>"]
